window.CatState.applyStoredCatProfile();
window.CatState.setInitialState();
window.CatInteraction.registerPointerTracking();
window.CatInteraction.registerCatMouseEvents();
window.CatInteraction.registerNameControls();
window.CatInteraction.registerSetupControls();
window.CatInteraction.registerWindowResizeControls();
window.CatMovement.registerRandomMovement();
window.CatMovement.registerBoundaryGuards();
